AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - spec/account_spec.rb
    - spec/feature_spec.rb
    - spec/transaction_spec.rb
    - spec/statement_spec.rb

Style/FormatString:
  Exclude:
    - lib/account.rb
    - lib/statement.rb

Style/FormatStringToken:
  Exclude:
    - lib/account.rb
    - lib/statement.rb

Style/NegatedIf:
  Exclude:
    - lib/transaction.rb
